default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  host: 127.0.0.1
  timeout: 5000

development:
  <<: *default
  database: development_database

test:
  <<: *default
  database: test_database

production:
  <<: *default
  database: production_database
