# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5811126631b613a712743fefef76add3f57dc5b863ee305f478ab2b82ce3fec818f64d8844252af2e015644a14b419176a35a4f18ff25fd3b6998195514838bc

test:
  secret_key_base: 8125503c224433c6a316be82324171217362f599ec35976973144aa74b770b4b7a622fd6c57ed143ef7a8ea0105d739e76b6d0ac8a4c419e9d3ecf8c8ca4c21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
